name: My Config
version: 1.0.0
schema: v1

models:
  - name: gpt-5.4
    provider: openai
    apiBase: https://tokenflux.dev/v1
    apiKey: sk-d19866409b6d096ff624ab285182f341dc13052d9c730330e9484623bc3f9dca
    model: gpt-5.4
    roles:
      - chat
      - edit
      - apply

  - name: gpt-5.5
    provider: openai
    apiBase: https://tokenflux.dev/v1
    apiKey: sk-d19866409b6d096ff624ab285182f341dc13052d9c730330e9484623bc3f9dca
    model: gpt-5.5
    roles:
      - chat
      - edit
      - apply
